bola/urls.py
from django.urls import path
from .import views
from django.urls import path, re_path
from django.views.generic import TemplateView
# from .views import ViewsToBeImported


app_name = "bola"

urlpatterns = [
    path('',views.home,name='home'),
    path('properties/',views.properties,name='properties'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('blog/',views.blog,name='blog'),
    path('blog/<int:pk>/', views.detail_page,name='detail-page'),
    path('blogpost/',views.blogpost,name='blogpost'),
    path('page404/',views.page404,name='page404')
    

]

bolabule/urls.py
from django.contrib import admin
from bola import views
from django.urls import path,include
from bola.views import blog, detail_page
from django.conf import settings
from django.conf.urls.static import static
from bola.views import page404

handler404 = page404

urlpatterns = [
    path('', include('bola.urls', namespace='bola')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('bola.urls', namespace='blog'))
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bola/models.py
from django.db import models
from django.db.models import Model
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from autoslug import AutoSlugField


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextField(blank=True,null=True,unique=False)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = RichTextField(blank=True,null=True,unique=False)  
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now_add=True)
    cover_image_url = models.URLField(max_length=200, blank=True)
    blockquote = models.CharField(max_length=150, blank=True,null=True)
    # slug = AutoSlugField(populate_from='title')

   
    
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('bola:detail-page', kwargs={'pk': self.pk,})

bola/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import Post
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView,
    )

# Create your views here.
def home (request):
    return render(request,'bola/home.html')

def blogpost (request):
    return render(request,'bola/blogpost.html')

def about (request):
    return render(request,'bola/about.html')

def properties (request):
    return render(request,'bola/properties.html')

def contact (request):
    return render(request,'bola/contact.html')

def blog (request):
    posts = Post.objects.all()
    return render(request,'bola/blog.html', {'posts': posts})

def detail_page (request, pk):
    post = Post.objects.get(pk=pk)
    return render (request,'bola/detail_page.html', {'post': post})

def page404 (request, exception):
    return render(request,'bola/page404.html', status=404)

bola/templates/bola/blog.html
{% load static %}
<!DOCTYPE html>

 <html dir="ltr" lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="advanced custom search, agency, agent, business, clean, corporate, directory, google maps, homes, idx agent, listing properties, membership packages, property, real broker, real estate, real estate agent, real estate agency, realtor">
<meta name="description" content="BOLA ADEBULE & CO">
<meta name="CreativeLayers" content="ATFN">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<title>BOLA ADEBULE & CO</title>
<link href="{% static 'images/favicon.ico' %}" sizes="128x128" rel="shortcut icon" type="image/x-icon" />           
<link href="{% static 'images/favicon.ico' %}" sizes="128x128" rel="shortcut icon" />
</head>
<body>
<div class="wrapper">
	<div class="preloader"></div>

	<!-- Main Header Nav -->
	<header class="header-nav menu_style_home_one style2 navbar-scrolltofixed stricky main-menu">
		<div class="container-fluid p0">
		    <!-- Ace Responsive Menu -->
		    <nav>
		        <!-- Menu Toggle btn-->
		        <div class="menu-toggle">
		            {% comment %} <img class="nav_logo_img img-fluid" src="{% static 'images/header-logo.png' %}" alt="header-logo.png"> {% endcomment %}
		            <button type="button" id="menu-btn">
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		            </button>
		        </div>
				<a href="#" class="navbar_brand float-left dn-smd">
		            <img class="logo1 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="header-logo.png">
		            {% comment %} <img class="logo2 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="header-logo2.png"> {% endcomment %}
		            <span>BOLA ADEBULE & CO.</span>
		        </a>
		     
				<ul id="respMenu" class="ace-responsive-menu text-right" data-menu-style="horizontal">
					<li>
		                <a href="{% url 'bola:home' %}"><span class="title">Home</span></a>		                
		            </li>
		           
		            <li>
		                <a href="{% url 'bola:about' %}"><span class="title">About Us</span></a>
		               
		            </li>
		            <li>
		                <a href="{% url 'bola:properties' %}"><span class="title">Properties</span></a>
		                
		            </li>
		            <li>
		                <a href="{% url 'bola:blog' %}"><span class="title">Blog</span></a>
		               
		            </li>
		            <li class="last">
		                <a href="{% url 'bola:contact' %}"><span class="title">Contact</span></a>
		            </li>
	                <li class="list-inline-item list_s"><a href="#" class="" data-toggle="modal" data-target=".bd-example-modal-lg"> <span class="dn-lg"></span></a></li>
	                <!-- <li class="list-inline-item add_listing"><a href=""><span class=""></span><span class="dn-lg"> B A C</span></a></li> -->
		        </ul>
		      
		    </nav>
		</div>
	</header>
	<!-- Modal -->
	
	<!-- Main Header Nav For Mobile -->
	<div id="page" class="stylehome1 h0">
		<div class="mobile-menu">
			<div class="header stylehome1">
				<div class="main_logo_home2 text-center">
		            <!-- <img class="nav_logo_img img-fluid mt20" src="images/header-logo2.png" alt="header-logo2.png"> -->
		            <span class="mt20">BOLA ADEBULE & CO.</span>
				</div>
				<ul class="menu_bar_home2">
	                <li class="list-inline-item list_s"><a href="page-register.html"><span class=""></span></a></li>
					<li class="list-inline-item"><a href="#menu"><span></span></a></li>
				</ul>
			</div>
		</div><!-- /.mobile-menu -->
		<nav id="menu" class="stylehome1">
			<ul><li><a href="{% url 'bola:home' %}">Home</a></li>
				<li><a href="{% url 'bola:about' %}">About Us</a></li> 
				<li><a href="{% url 'bola:properties' %}">Properties</a></li> 
				<li><a href="{% url 'bola:blog' %}">Blog</a></li>
				<li><a href="{% url 'bola:contact' %}">Contact</a></li>  
				                     
				<!-- <li class="cl_btn"><a class="btn btn-block btn-lg btn-thm circle" href="#"><span></span> B A C</a></li> -->
			</ul>
		</nav>
	</div>

	<!-- Main Blog Post Content -->
	<section class="blog_post_container bgc-f7">
		<div class="container">
			<div class="row">
				<div class="col-xl-6">
					<div class="breadcrumb_content style2">
						<ol class="breadcrumb">
						    <li class="breadcrumb-item"><a href="{% url 'bola:home' %}">Home</a></li>
						    <!-- <li class="breadcrumb-item active text-thm" aria-current="page">Simple Listing – Grid View</li> -->
						</ol>
						<h2 class="breadcrumb_title">Blog</h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-8">
					<div class="main_blog_post_content">

						
{% comment %} ------------------------------------------------------------------------Fist Post ------------------------------------------------------------------- {% endcomment %}
 {% for post in posts %} 
<div class="for_blog feat_property">
	<div class="thumb">
		{% comment %} <div class="blog_tag">{{ post.title_tag }}</div> {% endcomment %}
	</div>
	<div class="details">
		<div class="tc_content">
			<h4 class="mb15">{{ post.title }}</h4>
			{% comment %} <p style="font-style:bold;">{{ post.content }}</p> {% endcomment %}
			<p>{{ post.body|safe }}</p>
		</div>
		<div class="fp_footer">
			<ul class="fp_meta float-left mb0">
				<li class="list-inline-item"><a href="#">{{ post.author }}</a></li>
				<li class="list-inline-item"><a href="#"><span class="flaticon-calendar pr10"></span>{{ post.created_date }}</a></li>
			</ul>
			<a class="fp_pdate float-right text-thm" href="{{ post.get_absolute_url }}">Read More <span class="flaticon-next"></span></a>
		</div>
	</div>
</div>
{% endfor %}
{% comment %} ---------------------------------------------------------------------------end of Post----------------------------------------------------------------- {% endcomment %}

						<div class="row">
							<div class="col-lg-12">
								<div class="mbp_pagination mt20">
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- Our Footer -->
<!-- Our Footer -->
<section class="footer_one">
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-md-6 col-lg-3 col-xl-3 pr0 pl0">
				<div class="footer_about_widget">
					<h4>BOLA ADEBULE & CO</h4>
					<!-- <p>We’re reimagining how you buy, sell and rent. It’s now easier to get into a place you love. So let’s do this, together.</p> -->
				</div>
			</div>
			<div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
				<div class="footer_qlink_widget">
					<h4>Quick Links</h4>
					<ul class="list-unstyled">
						<li><a href="{% url 'bola:about' %}">About Us</a></li>
						<li><a href="{% url 'bola:contact' %}">Support Center</a></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
				<div class="footer_contact_widget">
					<h4>Contact Us</h4>
					<ul class="list-unstyled">
						<li><a href="#">bolaadebuleandco@gmail.com</a></li>
						<li><a href="#">33, Oguntona crescent</a></li>
						<li><a href="#">Gbagada phase 1</a></li>
						{% comment %} <li><a href="#"></a></li> {% endcomment %}
						<li><a href="#">Lagos.</a></li>
						<li><a href="#">+234-806 661 2255</a></li>
						<li><a href="#">+234-802 582 0364</a></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-6 col-md-6 col-lg-3 col-xl-3">
				<div class="footer_social_widget">
					<h4>Follow us</h4>
					<ul class="mb30">
						<li class="list-inline-item"><a href="https://www.facebook.com/bolaadebuleandcompany?mibextid=LQQJ4d"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/bolaadebulepropertyplace/"><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="https://t.me/bolaadebulepropertyplace/"><i class="fa fa-telegram"></i></a></li>
						<li class="list-inline-item"><a href="mailto:BOLAADEBULEANDCO@GMAIL.COM"><i class="fa fa-google"></i></a></li>
						<li class="list-inline-item"><a href="http://jiji.ng/sellerpage-2765697"><i class="fa-shopping-cart"></i></a></li>
					</ul>
					<form class="footer_mailchimp_form">
						 <div class="form-row align-items-center">
							<div class="col-auto">
							</div>
							<div class="col-auto">
							</div>
						  </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Our Footer Bottom Area -->
<section class="footer_middle_area pt40 pb40">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-xl-6">
				<div class="footer_menu_widget">
					<ul>
						<li class="list-inline-item"><a href="{% url 'bola:home' %}">Home</a></li>
						<li class="list-inline-item"><a href="{% url 'bola:properties' %}">Properties</a></li>
						<li class="list-inline-item"><a href="{% url 'bola:about' %}">About Us</a></li>
						<li class="list-inline-item"><a href="{% url 'bola:blog' %}">Blog</a></li>
						<li class="list-inline-item"><a href="{% url 'bola:contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-6 col-xl-6">
				<div class="copyright-widget text-right">
					<p>©  2023 BOLA ADEBULE & CO.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<a class="scrollToHome" href="#"><i class="flaticon-arrows"></i></a>
</div>
<!-- Wrapper End -->
{% comment %} WHATSAPP API STARTS HERE {% endcomment %}
<script>
    var url = 'https://wati-integration-service.clare.ai/ShopifyWidget/shopifyWidget.js?56617';
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = url;
    var options = {
  "enabled":true,
  "chatButtonSetting":{
      "backgroundColor":"#4dc247",
      "ctaText":"",
      "borderRadius":"25",
      "marginLeft":"0",
      "marginBottom":"50",
      "marginRight":"50",
      "position":"right"
  },
  "brandSetting":{
      "brandName":"Bola Adebule & Co",
      "brandSubTitle":"Welcome ",
	  "brandImg":"http://www.bolaadebule.com/static/images/header-logo2.png",
      "welcomeText":"Hi there!\nWelcome to Bola Adebule & co\nHow can I help you?",
      "messageText":"Hello, I have a question about {{page_link}}",
      "backgroundColor":"#0a5f54",
      "ctaText":"Start Chat",
      "borderRadius":"25",
      "autoShow":false,
      "phoneNumber":"2348025820364"
  }
};
    s.onload = function() {
        CreateWhatsappChatWidget(options);
    };
    var x = document.getElementsByTagName('script')[0];
    x.parentNode.insertBefore(s, x);
</script>
{% comment %} WHATSAPP API ENDS HERE {% endcomment %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mmenu.all.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ace-responsive-menu.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/isotop.js' %}"></script>
<script type="text/javascript" src="{% static 'js/snackbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/simplebar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scrollto.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-scrolltofixed-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.counterup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pricing-slider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/timepicker.js' %}"></script>
<!-- Custom script for all pages --> 
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
{% comment %} {% endfor %}
{% endblock %} {% endcomment %}
</body>
</html>

bola/templates/bola/contact.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="advanced custom search, agency, agent, business, clean, corporate, directory, google maps, homes, idx agent, listing properties, membership packages, property, real broker, real estate, real estate agent, real estate agency, realtor">
<meta name="description" content="BOLA ADEBULE & CO">
<meta name="CreativeLayers" content="ATFN">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<title>BOLA ADEBULE & CO</title>
<link href="{% static 'images/favicon.ico' %}" sizes="128x128" rel="shortcut icon" type="image/x-icon" />           
<link href="{% static 'images/favicon.ico' %}" sizes="128x128" rel="shortcut icon" />

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="wrapper">
	<div class="preloader"></div>
	<!-- Main Header Nav -->
	<header class="header-nav menu_style_home_one style2 navbar-scrolltofixed stricky main-menu">
		<div class="container-fluid p0">
		    <!-- Ace Responsive Menu -->
		    <nav>
		        <!-- Menu Toggle btn-->
		        <div class="menu-toggle">
		            <img class="nav_logo_img img-fluid" src="{% static 'images/header-logo.png' %}" alt="header-logo.png">
		            <button type="button" id="menu-btn">
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		            </button>
		        </div>
		        <a href="#" class="navbar_brand float-left dn-smd">
		            <img class="logo1 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="header-logo.png">
		            <!-- <img class="logo2 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="header-logo2.png"> -->
		            <span>BOLA ADEBULE & CO.</span>
		        </a>
		        <!-- Responsive Menu Structure-->
		        <!--Note: declare the Menu style in the data-menu-style="horizontal" (options: horizontal, vertical, accordion) -->
		        <ul id="respMenu" class="ace-responsive-menu text-left" data-menu-style="horizontal">
					<li>
		                <a href="{% url 'bola:home' %}"><span class="title">Home</span></a>		                
		            </li>
		           
		            <li>
		                <a href="{% url 'bola:about' %}"><span class="title">About Us</span></a>
		               
		            </li>
		            <li>
		                <a href="{% url 'bola:properties' %}"><span class="title">Properties</span></a>
		                
		            </li>
		            <li>
		                <a href="{% url 'bola:blog' %}"><span class="title">Blog</span></a>
		               
		            </li>
		            <li class="last">
		                <a href="{% url 'bola:contact' %}"><span class="title">Contact</span></a>
		            </li>
					 <!-- <li class="list-inline-item add_listing home5 float-right"><a href="#"><span class=""></span><span class="dn-lg"></span></a></li> -->
					 <li class="list-inline-item list_s float-right">
						 <!-- <a href="#" class="" data-toggle="modal" data-target=".bd-example-modal-lg"> <span class="dn-lg"></span></a> -->
					 </li>
				 </ul>
		            
		    </nav>
		</div>
	</header>
	<!-- Modal -->
	<!-- Main Header Nav For Mobile -->
	<div id="page" class="stylehome1 h0">
		<div class="mobile-menu">
			<div class="header stylehome1">
				<div class="main_logo_home2 text-center">
		            {% comment %} <img class="nav_logo_img img-fluid mt20" src="images/header-logo2.png" alt="header-logo2.png"> {% endcomment %}
		            <span class="mt20">BOLA ADEBULE & CO.</span>
				</div>
				<ul class="menu_bar_home2">
	                <li class="list-inline-item list_s"><a href=""><span class=""></span></a></li>
					<li class="list-inline-item"><a href="#menu"><span></span></a></li>
				</ul>
			</div>
		<!--</div>/.mobile-menu  -->
		<nav id="menu" class="stylehome1">
			<ul>
				<li><a href="{% url 'bola:home' %}">Home</a></li>
				<li><a href="{% url 'bola:about' %}">About Us</a></li> 
				<li><a href="{% url 'bola:properties' %}">Properties</a></li> 
				<li><a href="{% url 'bola:blog' %}">Blog</a></li>
				<li><a href="{% url 'bola:contact' %}">Contact</a></li>              
				<!-- <li class="cl_btn"><a class="btn btn-block btn-lg btn-thm circle" href="#"><span></span></a></li> -->
			</ul>
		</nav>
	</div>

	<!-- Inner Page Breadcrumb -->
	<section class="inner_page_breadcrumb">
		<div class="container">
			<div class="row">
				<div class="col-xl-6">
					<div class="breadcrumb_content">
						<ol class="breadcrumb">
						    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
						    <li class="breadcrumb-item active" aria-current="contact.html">Contact</li>
						</ol>
						<h4 class="breadcrumb_title">Contact Us</h4>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Our Contact -->
	<section class="our-contact pb0 bgc-f7">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-xl-4">
					<div class="contact_localtion">
						<h4>Contact Us</h4>
						<p>Contact your trusted housing partner to make your ideas come true.</p>
						<div class="content_list">
							<h5>Address</h5>
							<p>33, Oguntona crescent,
								<br>Gbagada phase1,
								
							
								<br>Lagos.</p>
						</div>
						<div class="content_list">
							<h5>Phone</h5>
							<p>Tel +234-8066612255</p>
							<p>Tel +234-8025820364</p>
						</div>
						<div class="content_list">
							<h5>Mail</h5>							
							<p>bolaadebuleandco@gmail.com</p>
						</div>
						<div class="content_list">
							<!-- <h5>Skype</h5>
							<p>BOLAADEBULEANDCO.com</p> -->
						</div>
						<h5>Follow Us</h5>
						<ul class="contact_form_social_area">
							<li class="list-inline-item"><a href="https://www.facebook.com/bolaadebuleandcompany?mibextid=LQQJ4d"><i class="fa fa-facebook"></i></a></li>
							<li class="list-inline-item"><a href="https://t.me/bolaadebulepropertyplace/"><i class="fa fa-telegram"></i></a></li>
							<li class="list-inline-item"><a href="https://www.instagram.com/bolaadebulepropertyplace/"><i class="fa fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="mailto:BOLAADEBULEANDCO@GMAIL.COM"><i class="fa fa-google"></i></a></li>
							<li class="list-inline-item"><a href="http://jiji.ng/sellerpage-2765697"><i class="fa fa-shopping-cart"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid p0 mt50">
			<div class="row">
				<div class="col-lg-12">
					<div class="h600" id="map-canvas"></div>
				</div>
			</div>
		</div>
	</section>


<!-- Wrapper End -->
{% comment %} WHATSAPP API STARTS HERE {% endcomment %}
<script>
    var url = 'https://wati-integration-service.clare.ai/ShopifyWidget/shopifyWidget.js?56617';
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = url;
    var options = {
  "enabled":true,
  "chatButtonSetting":{
      "backgroundColor":"#4dc247",
      "ctaText":"",
      "borderRadius":"25",
      "marginLeft":"0",
      "marginBottom":"50",
      "marginRight":"50",
      "position":"right"
  },
  "brandSetting":{
      "brandName":"Bola Adebule & Co",
      "brandSubTitle":"Welcome ",
	  "brandImg":"http://www.bolaadebule.com/static/images/header-logo2.png",
      "welcomeText":"Hi there!\nWelcome to Bola Adebule & co\nHow can I help you?",
      "messageText":"Hello, I have a question about {{page_link}}",
      "backgroundColor":"#0a5f54",
      "ctaText":"Start Chat",
      "borderRadius":"25",
      "autoShow":false,
      "phoneNumber":"2348025820364"
  }
};
    s.onload = function() {
        CreateWhatsappChatWidget(options);
    };
    var x = document.getElementsByTagName('script')[0];
    x.parentNode.insertBefore(s, x);
</script>
{% comment %} WHATSAPP API ENDS HERE {% endcomment %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mmenu.all.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ace-responsive-menu.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/isotop.js' %}"></script>
<script type="text/javascript" src="{% static 'js/snackbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/simplebar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scrollto.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-scrolltofixed-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.counterup.js' %}"></script>
<script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pricing-slider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/timepicker.js' %}"></script>
<!-- Custom script for all pages --> 
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

bola/templates/bola/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home  {% endblock %}  

{% block content %}

{% endblock %}

{% load static %}

bola/templates/bola/page404.html
{% comment %} {% extends "./base.html" %} {% endcomment %}
{% load static %}
<!Doctype html>
<html>
<body>
    <h1>Oops! Page Not Found</h1>
    <p>The page you are looking for does not exist.</p>
</body>
</html>